# Generated by Django 4.2.3 on 2023-07-20 00:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator("^(?![\\s'-])(?!.*[\\s'-]{2})[A-Za-z '-]+(?<![\\s'-])\\Z"), django.core.validators.MinLengthValidator(2)], verbose_name='Name')),
                ('description', models.TextField(blank=True, error_messages={'null': 'Description field cannot be null, use an empty string instead.'}, help_text='Longer textfield containing a description of this menu item.', max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Menu Item',
            },
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^(?![\\s'-])(?!.*[\\s'-]{2})[A-Za-z '-]+(?<![\\s'-])\\Z"), django.core.validators.MinLengthValidator(2)], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='location_index',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Location Index'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.PositiveIntegerField(choices=[(0, 'Appetiser'), (1, 'Starter'), (2, 'Main Course'), (3, 'Dessert')], verbose_name='Course')),
                ('notes', models.TextField(blank=True, error_messages={'null': 'Notes field cannot be null, use an empty string instead.'}, help_text='Longer textfield containing any notes to the kitchen about how to prepare this order.', max_length=200, verbose_name='Notes')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='smartserve.menuitem')),
                ('seat_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='smartserve.seatbooking')),
            ],
            options={
                'verbose_name': 'Ordered Menu Item',
            },
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='ordered_menu_items',
            field=models.ManyToManyField(blank=True, help_text='The set of menu items ordered by this seat booking.', related_name='+', through='smartserve.Order', to='smartserve.menuitem', verbose_name='Ordered Menu Items'),
        ),
    ]
