# Generated by Django 4.2.1 on 2023-06-02 17:00

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import smartserve.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('smartserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, default=smartserve.models.utils.generate_employee_id, error_messages={'unique': 'A user with that ID already exists.'}, max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d+\\Z'), django.core.validators.MinLengthValidator(6)], verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=75, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Is Admin?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=75, verbose_name='Last Name'),
        ),
    ]
