# Generated by Django 4.2.1 on 2023-06-06 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.ForeignKey(help_text='The Table this seat is at.', on_delete=django.db.models.deletion.CASCADE, related_name='_seats', to='smartserve.table', verbose_name='Table')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
