# Generated by Django 4.2.3 on 2023-07-21 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartserve', '0002_menuitem_alter_restaurant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='available_at_restaurants',
            field=models.ManyToManyField(blank=True, help_text='The set of restaurants that this menu item is available at.', related_name='menu_items', to='smartserve.restaurant', verbose_name='Available At Restaurants'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seat_booking',
            field=models.ForeignKey(limit_choices_to={'seat__table__restaurant__in': models.F('menu_item__available_at_restaurants')}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='smartserve.seatbooking'),
        ),
    ]
