# Generated by Django 4.2.1 on 2023-06-02 20:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartserve', '0002_alter_user_options_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+\\Z'), django.core.validators.MinLengthValidator(2)], verbose_name='Name')),
                ('employees', models.ManyToManyField(related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant',
            },
        ),
    ]
