# Generated by Django 4.2.1 on 2023-06-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartserve', '0002_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start Date & Time')),
                ('end', models.DateTimeField(verbose_name='End Date & Time')),
            ],
            options={
                'verbose_name': 'Booking',
            },
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'verbose_name': 'Seat'},
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(help_text='The overall Booking that this Seat Booking is a part of.', on_delete=django.db.models.deletion.CASCADE, related_name='seat_bookings', to='smartserve.booking', verbose_name='Booking')),
                ('seat', models.ForeignKey(help_text='The Seat that this is a booking for.', on_delete=django.db.models.deletion.PROTECT, related_name='seat_bookings', to='smartserve.seat', verbose_name='Seat')),
            ],
            options={
                'verbose_name': 'Seat Booking',
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('end__gt', models.F('start'))), name='check_start_end'),
        ),
        migrations.AddConstraint(
            model_name='seatbooking',
            constraint=models.UniqueConstraint(fields=('seat', 'booking'), name='unique_seat_booking'),
        ),
    ]
