# Generated by Django 4.2.3 on 2023-07-21 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartserve', '0003_menuitem_available_at_restaurants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='employees',
            field=models.ManyToManyField(blank=True, help_text='The set of employees at this restaurant.', related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='Employees'),
        ),
    ]
