# Generated by Django 4.2.1 on 2023-06-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartserve', '0003_booking_alter_seat_options_seatbooking_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='check_start_end',
        ),
        migrations.AddField(
            model_name='seat',
            name='location_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Location Index'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('end__gt', models.F('start'))), name='check_start_end', violation_error_message='Start Date & Time must be before End Date & Time.'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('table', 'location_index'), name='unique_table_location_index'),
        ),
    ]
