# Generated by Django 4.2.1 on 2023-06-02 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartserve', '0003_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
