# Generated by Django 4.2.1 on 2023-06-02 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartserve', '0004_alter_restaurant_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='employees',
            field=models.ManyToManyField(blank=True, help_text='The set of restaurants that this user is employed at.', related_name='restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
